name: NuGet push

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            3.1.x
            6.0.x

      - run: ./build.ps1 --target=push --nuget-api-key=${{ secrets.nuget_api_key }} --nuget-source=${{ secrets.nuget_source }}
        shell: pwsh

      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ./.output/**/*

      - run: ./build.ps1 --target=push --nuget-api-key=${{ secrets.myget_api_key }} --nuget-source=${{ secrets.myget_source }} --exclusive
        shell: pwsh
